GET http://localhost:3001/api/members
Accept: application/json

###
POST http://localhost:3001/api/members
Content-Type: application/json

{
  "firstName": "Hanif",
  "lastName": "Carroll",
  "email": "HanifCarroll@gmail.com",
  "phone": "941-286-5903",
  "status": "Active"
}

